<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationHighDpiMode>SystemAware</ApplicationHighDpiMode>
    <ApplicationIcon>app.ico</ApplicationIcon>
    <Version>1.2.4</Version>
    <SatelliteResourceLanguages>zh-Hans</SatelliteResourceLanguages>
    <AssemblyName>PcCompanionMonitor</AssemblyName>
    <RootNamespace>PcCompanionMonitor</RootNamespace>
  </PropertyGroup>
</Project>
