<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <ApplicationHighDpiMode>SystemAware</ApplicationHighDpiMode>
    <ApplicationIcon>app.ico</ApplicationIcon>
    <AssemblyTitle>云曦PC统计 安装程序</AssemblyTitle>
    <Product>云曦PC统计 安装程序</Product>
    <Version>1.2.9.1</Version>
    <SatelliteResourceLanguages>zh-Hans</SatelliteResourceLanguages>
    <AssemblyName>CloudXiPcMonitorInstaller</AssemblyName>
    <RootNamespace>CloudXiPcMonitor.Installer</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="..\DesktopCompanionMonitor\PCCompanionMonitor.exe"
                      LogicalName="CloudXiPcMonitor.App.exe" />
  </ItemGroup>

</Project>
